#!/bin/bash 

rm -fr bibtex/src-*
cp bibtex/inst/grammar/bibparse.y bibtex/src/
cp bibtex/inst/grammar/biblex.l bibtex/src/
cd bibtex/src

bison -vtd bibparse.y -o bibparse.c
lex -l -t biblex.l > biblex.c
rm bibparse.y
rm biblex.l
mv bibparse.output ../inst/
cd ../..

R CMD build bibtex 
R CMD INSTALL bibtex_0.2-1.tar.gz
rm -fr bibtex/src-*

                                          
