#!/bin/bash 

cp parser/inst/grammar/gram.y parser/src/
cd parser/src
bison -vt gram.y -o gram.c
mv gram.output ../inst/grammar
rm gram.y
cd ../..

R CMD build parser

# remove the include file (volatile file, not svn'ed)
R CMD INSTALL parser_0.0-10.tar.gz

