#!/bin/bash 

cp bibtex/inst/grammar/bibparse.y bibtex/src/
cp bibtex/inst/grammar/biblex.l bibtex/src/
cd bibtex/src

bison -vtd bibparse.y -o bibparse.c
lex -l -t biblex.l > biblex.c
rm bibparse.y
rm biblex.l
mv bibparse.output ../inst/
cd ../..

R CMD build bibtex 
sudo /usr/local/lib/R/bin/R CMD INSTALL bibtex_0.1-2.tar.gz

